# Example: https://github.com/rodrigokamada/angular-github-actions
# https://github.com/peaceiris/actions-gh-pages
name: GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run linter
        run: yarn lint

      - name: Build
        run: yarn build:ci
